export const CREATE_SUMMARY_REQUEST = "CREATE_SUMMARY_REQUEST";
export const CREATE_SUMMARY_SUCCESS = "CREATE_SUMMARY_SUCCESS";
export const CREATE_SUMMARY_RESET = "CREATE_SUMMARY_RESET";
export const CREATE_SUMMARY_FAIl = "CREATE_SUMMARY_FAIL";

export const ALL_SUMMARY_REQUEST = "ALL_SUMMARY_REQUEST";
export const ALL_SUMMARY_SUCCESS = "ALL_SUMMARY_SUCCESS";
export const ALL_SUMMARY_FAIL = "ALL_SUMMARY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
